### ISSUE TITLE
Remove all frames from node_modules

### ISSUE THREAD

**Issue by jawadst** [AndreasMadsen/clarify#12]
Most of the useless frames are from `node_modules` so it would be great to have an option to disable all frames from there and only see traces from our own code.

More generally, an option to customize what frames should be removed (maybe by regular expressions) would be great.

We could use an env variable for passing that regular expression to clarify (like `CLARIFY_FILTER=*` would be the default)

Jawad

**Comment by AndreasMadsen** [comment]
I would recommend that you make your own module. Feel free to be inspired by this one.

Dublicate of: https://github.com/AndreasMadsen/clarify/issues/10
