### ISSUE TITLE
Limit number of lines

### ISSUE THREAD

**Issue by lazywithclass** [AndreasMadsen/clarify#3]
First of all thanks for this project!

I was wondering if you're interested in accepting a pull request that would allow to limit the number of lines of a stack trace, something like 

```javascript
chain.filter.attach(function (error, frames) {
  frames = frames.filter(function (callSite) {
    var name = callSite && callSite.getFileName();
    return (name && name.indexOf(sep) !== -1);
  });
  // limit to 10 lines
  return frames.slice(0, 10);
});
```

I would make sure that I would only slice lines that are part of a stack trace, but I hope I made my point clear with that simple example.

If you're happy with this I would write a pull request, let me know.

**Comment by AndreasMadsen** [comment]
hmm, this should already be supported by the `Error.stackTraceLimit` which by default is 10. Maybe try
```js
console.log(Error.stackTraceLimit);
```
You properly you have the `Error.stackTraceLimit` parameter overwritten somewhere, or you are calling node with the `--stack_trace_limit` argument.

**Comment by lazywithclass** [comment]
Wow, I didn't know about that, the `coffee-script` module (and a few others) are setting it to `Infinity`.

I've set it via command line and works ok. Thank you ;D
