### ISSUE TITLE
electron support

### ISSUE THREAD

**Issue by cdaringe** [AndreasMadsen/clarify#6]
howdy.  i see that clarify is itself a pretty tiny module.  it would seem useful to perhaps also support electron?  trouble is that the filter as used here isn't entirely relevant any longer (e.g. most folks, myself included, use electron-prebuilt which gives a fully qualified path to the electron binary).  anyway, i can add my own filter now that i see how this all clicks together, but thought i'd at least shout out the request! thanks

**Comment by AndreasMadsen** [comment]
This will be very hard  for me to test. Why not just make a `clarify-electron` module? The `stack-chain` module allows more than one `filter` function.

**Comment by cdaringe** [comment]
Agreed.
